"""
01 — Static vs runtime: the distinction everything else depends on.

THE ONE-PARAGRAPH VERSION
-------------------------
Python annotations do NOTHING at runtime. `def f(x: int)` accepts a string, a
list, or a socket without complaint. mypy reads annotations and checks them
before your code runs; the interpreter ignores them entirely.

That means annotations are a *proof about code you control* and a *lie about
data you receive*. The same `x: int` is load-bearing inside your package and
worthless on a JSON payload from an HTTP client or an LLM.

So there are two separate tools for two separate jobs:

    STATIC (mypy)      proves internal consistency. Free at runtime.
                       Catches: wrong argument order, None where a value was
                       required, a refactor that missed a call site.

    RUNTIME (Pydantic) validates untrusted data at a boundary. Costs CPU.
                       Catches: the API returned null for a required field,
                       the model emitted "0.85" instead of 0.85, a client
                       sent an extra field you should reject.

Using one where the other belongs is the most common typing mistake in
production Python. Runtime-validating your own internal function arguments is
wasted CPU and noise. Statically typing untrusted input is a comforting lie.

Run:  python 01_static_vs_runtime.py
      mypy --strict 01_static_vs_runtime.py
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, cast

from typing_lab import (
    ChunkId,
    Completion,
    CompletionPayload,
    DeploymentName,
    DocId,
    FinishReason,
    Usage,
    banner,
    section,
    show,
)


# ---------------------------------------------------------------------------
# PART 1 — annotations do nothing
# ---------------------------------------------------------------------------

def add_scores(a: float, b: float) -> float:
    return a + b


def part1_annotations_are_inert() -> None:
    banner("PART 1 — annotations are not enforced at runtime")

    show("add_scores(1.5, 2.5)", add_scores(1.5, 2.5))

    # This is a static type error that mypy reports, and the interpreter runs
    # happily — because `+` happens to be defined for strings.
    #
    # The `type: ignore` comment tells mypy we are doing this deliberately.
    # ALWAYS give it a specific error code and a reason; a bare `# type: ignore`
    # suppresses every future error on that line too, including ones you
    # would want to know about.
    bad = add_scores("1.5", "2.5")  # type: ignore[arg-type]  # deliberate demo
    show('add_scores("1.5", "2.5")', repr(bad))
    print("""
    No exception. `+` is defined for str, so Python does string concatenation
    and returns "1.52.5" where every downstream consumer expects a float.

    This is the shape of the whole class of bug: the failure surfaces far from
    its cause, as a weird value rather than an error. mypy catches it at the
    call site, in the editor, in CI — before it ever runs.""")

    show("__annotations__ at runtime", add_scores.__annotations__)
    print("    ...just a dict. Nothing reads it unless you write code that does.")


# ---------------------------------------------------------------------------
# PART 2 — the four boundaries
# ---------------------------------------------------------------------------

def part2_boundaries() -> None:
    banner("PART 2 — where each tool is load-bearing")

    print("""
    ┌──────────────────────────────────────────────────────────────────────┐
    │  BOUNDARY            │ trusted? │ static │ runtime validation        │
    ├──────────────────────────────────────────────────────────────────────┤
    │  1 HTTP request body │    no    │  weak  │  REQUIRED (Pydantic)      │
    │  2 LLM output (JSON) │    no    │  weak  │  REQUIRED (Pydantic)      │
    │  3 search index rows │    no    │  weak  │  REQUIRED at ingest       │
    │  4 config / env vars │    no    │  weak  │  REQUIRED, fail at start  │
    │  5 internal calls    │   YES    │ STRONG │  none — wasted CPU        │
    │  6 your own tests    │   YES    │ STRONG │  none                     │
    └──────────────────────────────────────────────────────────────────────┘

    BOUNDARY 2 IS THE ONE PEOPLE MISS. Everyone validates the HTTP request
    body. Almost nobody validates the LLM's JSON output with the same rigour —
    despite it being the least reliable data source in the system, because it
    is generated by a stochastic process that has never read your schema.

    A model that returns `{"confidence": "high"}` where you declared
    `confidence: float` will propagate that string through your entire
    pipeline and fail somewhere unrelated — a comparison, a serialisation, a
    metric. Validate it AT the boundary, where the error message can say
    "the model returned a string for confidence".""")


# ---------------------------------------------------------------------------
# PART 3 — TypedDict is a promise, not a check
# ---------------------------------------------------------------------------

def parse_payload_unsafe(raw: str) -> CompletionPayload:
    """THE LIE. `json.loads` returns `Any`; casting it to a TypedDict tells
    mypy 'trust me' and performs zero verification.

    Everything downstream now type-checks perfectly against data that may not
    match at all. You have converted a runtime error into a SILENT wrong
    answer, which is strictly worse.
    """
    return cast(CompletionPayload, json.loads(raw))


def part3_typeddict_is_not_validation() -> None:
    banner("PART 3 — TypedDict describes; it does not validate")

    good = '{"id":"c1","finish_reason":"stop","content":"hello"}'
    bad = '{"id":123,"finish_reason":"BANANA","content":null}'

    section("well-formed payload")
    p1 = parse_payload_unsafe(good)
    show("finish_reason", p1["finish_reason"])

    section("malformed payload — same code path, no complaint")
    p2 = parse_payload_unsafe(bad)
    show("id (declared str)", repr(p2["id"]))
    show("finish_reason (declared Literal)", repr(p2["finish_reason"]))
    show("content (declared str)", repr(p2["content"]))

    print("""
    mypy sees `p2["finish_reason"]` as a `FinishReason` and will let you write
    `if p2["finish_reason"] == "length":` with full confidence. At runtime it
    is "BANANA" and that branch silently never fires.

    THE RULE: `cast()` is an assertion YOU are making, with no evidence. It is
    appropriate when you have genuinely verified something the checker cannot
    see. It is a bug when used to silence a checker complaint about untrusted
    data — which is most of how it gets used.

    Grep your codebase for `cast(` and check each one against that test.""")


# ---------------------------------------------------------------------------
# PART 4 — how `Any` spreads
# ---------------------------------------------------------------------------

def part4_any_contagion() -> None:
    banner("PART 4 — Any is contagious, and silently disables checking")

    print("""
    `Any` is not "unknown type". It is "stop checking". Every expression
    involving an `Any` produces an `Any`, so one untyped boundary can silently
    disable checking across a whole call graph:

        data = json.loads(text)        # Any
        chunks = data["chunks"]        # Any
        first = chunks[0]              # Any
        score = first.score            # Any   <- .score may not exist
        top = score * 2                # Any
        rank(top)                      # accepted no matter what rank() wants

    mypy reports NOTHING here. Five lines, zero checking, and the annotation
    on `rank` provided no protection at all.

    WHERE Any COMES FROM, in rough order of frequency:
      json.loads / yaml.safe_load / pickle.loads
      an untyped third-party library (no py.typed marker, no stubs)
      **kwargs: Any
      a bare `cast()`
      an explicit `Any` someone added to silence an error

    THE DEFENCES:
      1. `disallow_any_explicit` / `disallow_any_generics` in mypy config for
         the strictest modules.
      2. `warn_return_any = true` — catches a function annotated `-> float`
         that actually returns an Any. This one has the highest catch rate
         per unit of noise, and it is on in --strict.
      3. Prefer `object` over `Any` when you truly do not know. `object` is
         the safe top type: you must narrow it before use, so the checker
         keeps working. `Any` is the unsafe one that turns checking off.""")

    section("object vs Any, in practice")

    def with_any(payload: Any) -> float:
        # mypy accepts every line of this — EXCEPT the return, because
        # `warn_return_any` (on in --strict) notices we are returning an Any
        # from a function declared `-> float`.
        #
        # VERIFIED: running `mypy --strict` on this file reports exactly one
        # error, and it is this line:
        #   error: Returning Any from function declared to return "float"
        #          [no-any-return]
        #
        # That is `warn_return_any` earning its place. It cannot see the bug
        # INSIDE the function (the subscript, the multiply — all unchecked),
        # but it catches the Any escaping at the boundary, which is enough to
        # make you look. Note it took a strict-mode flag to catch even that.
        return payload["score"] * 2  # type: ignore[no-any-return]  # the point

    def with_object(payload: object) -> float:
        # mypy REQUIRES narrowing before use. This is the point.
        if not isinstance(payload, dict):
            raise TypeError("expected a mapping")
        score = payload.get("score")
        if not isinstance(score, (int, float)):
            raise TypeError(f"score must be numeric, got {type(score).__name__}")
        return float(score) * 2

    show("with_any({'score': 3})", with_any({"score": 3}))
    show("with_object({'score': 3})", with_object({"score": 3}))
    try:
        with_object({"score": "high"})
    except TypeError as e:
        show("with_object({'score': 'high'})", f"TypeError: {e}")
    show("with_any({'score': 'high'})", repr(with_any({"score": "high"})))
    print("    ...`Any` silently returned 'highhigh'. `object` raised.")


# ---------------------------------------------------------------------------
# PART 5 — an adapter: the right shape for a boundary
# ---------------------------------------------------------------------------

class PayloadError(ValueError):
    """Raised when untrusted input does not match the expected shape.

    Note this is a DOMAIN error, not a typing error. The boundary's job is to
    convert 'the data is wrong' into an exception your error taxonomy already
    knows how to classify (see the failure-handling tutorial).
    """


VALID_FINISH: frozenset[str] = frozenset(
    {"stop", "length", "content_filter", "tool_calls"}
)


def parse_completion(raw: str, deployment: DeploymentName) -> Completion:
    """Hand-written validation, to show what Pydantic does for you in 06.

    THE SHAPE THAT MATTERS:
      * takes `str` (untrusted), returns a typed domain object
      * every field checked, with a message naming the field and what it got
      * unknown values rejected rather than passed through
      * returns an INTERNAL type, not the wire type

    After this function, the rest of the system is in typed territory and
    static checking is genuinely load-bearing. That transition is the entire
    purpose of a boundary.
    """
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        raise PayloadError(f"not valid JSON: {e}") from e

    if not isinstance(data, dict):
        raise PayloadError(f"expected an object, got {type(data).__name__}")

    content = data.get("content")
    if not isinstance(content, str):
        raise PayloadError(
            f"'content' must be a string, got {type(content).__name__}"
        )

    fr = data.get("finish_reason")
    if fr not in VALID_FINISH:
        # Rejecting an UNKNOWN value rather than passing it through is the
        # important half. A new API version adding a finish_reason should
        # produce a loud error, not a silently-skipped branch.
        raise PayloadError(
            f"'finish_reason' was {fr!r}; expected one of {sorted(VALID_FINISH)}"
        )
    finish: FinishReason = cast(FinishReason, fr)   # cast is EARNED here:
                                                    # we just checked membership

    usage_raw = data.get("usage", {})
    if not isinstance(usage_raw, dict):
        raise PayloadError("'usage' must be an object")
    pt, ct = usage_raw.get("prompt_tokens", 0), usage_raw.get("completion_tokens", 0)
    if not isinstance(pt, int) or not isinstance(ct, int):
        raise PayloadError("token counts must be integers")

    return Completion(
        text=content,
        finish_reason=finish,
        usage=Usage(prompt_tokens=pt, completion_tokens=ct),
        deployment=deployment,
    )


def part5_adapter() -> None:
    banner("PART 5 — a boundary adapter, and the one earned cast")

    dep = DeploymentName("gpt-4o-mini-prod")
    cases = {
        "valid": '{"content":"ok","finish_reason":"stop",'
                 '"usage":{"prompt_tokens":10,"completion_tokens":4}}',
        "unknown finish_reason": '{"content":"ok","finish_reason":"BANANA"}',
        "null content": '{"content":null,"finish_reason":"stop"}',
        "not JSON": "I'm sorry, I can't help with that.",
        "tokens as strings": '{"content":"ok","finish_reason":"stop",'
                             '"usage":{"prompt_tokens":"10"}}',
    }
    for label, raw in cases.items():
        try:
            c = parse_completion(raw, dep)
            show(label, f"OK  text={c.text!r} tokens={c.usage.total}")
        except PayloadError as e:
            show(label, f"REJECTED  {e}")

    print("""
    Note the fourth case: a refusal. The model returned prose where JSON was
    required, and the boundary rejects it with 'not valid JSON' rather than
    letting a string flow into code expecting a Completion.

    THE CAST ON LINE ~205 IS EARNED: we checked membership in VALID_FINISH
    immediately before, so the assertion to the checker is backed by a runtime
    check. That is the difference between a legitimate cast and a lie.""")


# ---------------------------------------------------------------------------
# PART 6 — what static typing actually catches
# ---------------------------------------------------------------------------

@dataclass
class Retriever:
    top_k: int = 5

    def search(self, query: str, groups: frozenset[str]) -> list[ChunkId]:
        return [ChunkId("c1")]


def part6_what_it_catches() -> None:
    banner("PART 6 — the bugs static typing actually catches")

    print("""
    Real bugs, in rough order of how often mypy catches them in practice:

    1. ARGUMENT ORDER / NAME after a refactor
         search(groups, query)  — both are "stringish", tests may pass with
         symmetric fixtures. NewType (DocId vs ChunkId) makes even same-typed
         swaps a checker error.

    2. None WHERE A VALUE IS REQUIRED
         `Optional[Chunk]` returned from a lookup, used without a check. This
         is the single largest category and the reason `strict_optional` is
         on by default.

    3. A MISSED CALL SITE
         You add a required parameter; mypy finds all 14 callers instantly.
         Grep finds 11 of them and misses the ones behind an alias.

    4. IMPOSSIBLE BRANCHES
         Comparing a Literal against a value not in its set, or an `if` on a
         union member already excluded. mypy flags the dead branch; tests
         never will, because the branch never runs.

    5. RETURN TYPE DRIFT
         A function annotated `-> Completion` that returns `None` on one path.
         Extremely common in error handling, and invisible until that path
         runs in production.

    WHAT IT DOES NOT CATCH, and it matters that you know:
      * wrong VALUES (a score of 1.5 where 0-1 was meant)
      * wrong LOGIC (retrieving the wrong chunks, correctly typed)
      * anything about untrusted input
      * anything behind an `Any`, a bare `cast`, or an untyped dependency

    Static typing is a proof of internal consistency. It says nothing about
    whether the thing you built is the right thing.""")


def main() -> None:
    part1_annotations_are_inert()
    part2_boundaries()
    part3_typeddict_is_not_validation()
    part4_any_contagion()
    part5_adapter()
    part6_what_it_catches()

    banner("SUMMARY")
    print("""
  * Annotations do nothing at runtime. mypy reads them; Python ignores them.
  * Static typing is load-bearing INSIDE your code; useless on untrusted data.
  * Runtime validation is load-bearing AT boundaries; wasted CPU internally.
  * The forgotten boundary is LLM OUTPUT — the least reliable data source in
    the system, validated less rigorously than the HTTP request body.
  * TypedDict describes a shape; it never checks one.
  * `cast()` is an unverified assertion. Legitimate only when you have just
    performed the check the checker cannot see.
  * `Any` means "stop checking" and spreads through every expression it
    touches. Prefer `object`, which forces narrowing.
  * Boundary adapters convert untrusted input into internal types, and that
    transition is where static checking starts being worth anything.
""")


if __name__ == "__main__":
    main()
